// Command readme writes this repository's README.md from bonsai-lint's own README at a release.
// Packagist shows this repository's README and resolves its relative links here, so they are made
// absolute, into bonsai-lint at that release.
//
//	go run ./internal/readme                    # bonsai-lint's latest release
//	go run ./internal/readme -ref v0.4.3        # a given release
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"
)

const repository = "https://github.com/ryckakas/bonsai-lint"

var (
	absolute = regexp.MustCompile(`^([a-z][a-z0-9+.-]*:|#|/)`)
	mdLink   = regexp.MustCompile(`(!?)\[([^\]]*)\]\(([^)\s]+)\)`)
	htmlImg  = regexp.MustCompile(`(<img\b[^>]*\bsrc=")([^"]+)(")`)
	codeSpan = regexp.MustCompile("`[^`]*`")
)

var client = &http.Client{Timeout: time.Minute}

func main() {
	ref := flag.String("ref", "", "the release tag, e.g. v0.4.3; bonsai-lint's latest release by default")
	source := flag.String("source", "", "a local copy of bonsai-lint's README.md at -ref, instead of downloading it")
	out := flag.String("out", "README.md", "the file to write")
	flag.Parse()

	err := generate(*ref, *source, *out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "readme:", err)
		os.Exit(1)
	}
}

func generate(ref, source, out string) error {
	if ref == "" && source != "" {
		return fmt.Errorf("-source needs the -ref it was taken from")
	}
	ref, err := release(ref)
	if err != nil {
		return err
	}
	text, err := readme(ref, source)
	if err != nil {
		return err
	}
	return os.WriteFile(out, []byte(render(text, ref)), 0o644)
}

func release(ref string) (string, error) {
	if ref != "" {
		return ref, nil
	}
	body, err := get("https://api.github.com/repos/ryckakas/bonsai-lint/releases/latest")
	if err != nil {
		return "", err
	}
	var latest struct {
		TagName string `json:"tag_name"`
	}
	if err := json.Unmarshal(body, &latest); err != nil || latest.TagName == "" {
		return "", fmt.Errorf("no latest release in GitHub's answer: %v", err)
	}
	return latest.TagName, nil
}

func readme(ref, source string) (string, error) {
	if source != "" {
		text, err := os.ReadFile(source)
		return string(text), err
	}
	text, err := get("https://raw.githubusercontent.com/ryckakas/bonsai-lint/" + ref + "/README.md")
	return string(text), err
}

// A token raises GitHub's rate limit for the API call, which CI's shared addresses can exhaust.
func get(url string) ([]byte, error) {
	request, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	if token := os.Getenv("GITHUB_TOKEN"); token != "" && strings.HasPrefix(url, "https://api.github.com/") {
		request.Header.Set("Authorization", "Bearer "+token)
	}
	response, err := client.Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, response.Status)
	}
	return io.ReadAll(io.LimitReader(response.Body, 1<<20))
}

func render(markdown, ref string) string {
	header := fmt.Sprintf("<!-- Generated by internal/readme from %s/blob/%s/README.md, so edit it there."+
		" LAUNCHERS.md documents this repository. -->\n\n", repository, ref)
	return header + absoluteLinks(strings.ReplaceAll(markdown, "\r\n", "\n"), ref)
}

// Links and images inside code are examples, so fenced blocks and code spans are left alone.
func absoluteLinks(markdown, ref string) string {
	var b strings.Builder
	fenced := false
	for _, line := range strings.SplitAfter(markdown, "\n") {
		fence := strings.HasPrefix(strings.TrimLeft(line, " \t"), "```")
		if fence {
			fenced = !fenced
		}
		if fenced || fence {
			b.WriteString(line)
			continue
		}
		b.WriteString(outsideCode(line, ref))
	}
	return b.String()
}

func outsideCode(line, ref string) string {
	var b strings.Builder
	last := 0
	for _, span := range codeSpan.FindAllStringIndex(line, -1) {
		b.WriteString(rewrite(line[last:span[0]], ref))
		b.WriteString(line[span[0]:span[1]])
		last = span[1]
	}
	b.WriteString(rewrite(line[last:], ref))
	return b.String()
}

func rewrite(text, ref string) string {
	text = mdLink.ReplaceAllStringFunc(text, func(match string) string {
		parts := mdLink.FindStringSubmatch(match)
		return parts[1] + "[" + parts[2] + "](" + target(parts[3], ref, parts[1] == "!") + ")"
	})
	return htmlImg.ReplaceAllStringFunc(text, func(match string) string {
		parts := htmlImg.FindStringSubmatch(match)
		return parts[1] + target(parts[2], ref, true) + parts[3]
	})
}

// Images come from raw.githubusercontent.com, since a blob URL is a page, not the image.
func target(url, ref string, image bool) string {
	if absolute.MatchString(url) {
		return url
	}
	url = strings.TrimPrefix(url, "./")
	if image {
		return strings.Replace(repository, "https://github.com/", "https://raw.githubusercontent.com/", 1) +
			"/" + ref + "/" + url
	}
	return repository + "/blob/" + ref + "/" + url
}
