package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRelativeLinksPointAtTheRelease(t *testing.T) {
	got := absoluteLinks("[rules](docs/scoring-rules.md#go) and [roadmap](./ROADMAP.md)\n", "v1.2.3")

	want := "[rules](https://github.com/ryckakas/bonsai-lint/blob/v1.2.3/docs/scoring-rules.md#go) and " +
		"[roadmap](https://github.com/ryckakas/bonsai-lint/blob/v1.2.3/ROADMAP.md)\n"
	if got != want {
		t.Fatalf("got %q", got)
	}
}

func TestImagesComeFromRawContent(t *testing.T) {
	got := absoluteLinks("![cover](docs/images/cover.jpg)\n<img src=\"editors/vscode/a.png\" width=\"600\">\n", "v1.2.3")

	want := "![cover](https://raw.githubusercontent.com/ryckakas/bonsai-lint/v1.2.3/docs/images/cover.jpg)\n" +
		"<img src=\"https://raw.githubusercontent.com/ryckakas/bonsai-lint/v1.2.3/editors/vscode/a.png\" width=\"600\">\n"
	if got != want {
		t.Fatalf("got %q", got)
	}
}

func TestAbsoluteLinksAndAnchorsStayAsTheyAre(t *testing.T) {
	text := "[site](https://bonsai.kauneckas.dev) [mail](mailto:a@b.c) [up](#install) [root](/x)\n"

	if got := absoluteLinks(text, "v1.2.3"); got != text {
		t.Fatalf("got %q", got)
	}
}

func TestCodeIsLeftAlone(t *testing.T) {
	text := "Write `[x](y.md)` like this:\n```html\n<img src=\"./logic.ts\">\n[x](y.md)\n```\n"

	if got := absoluteLinks(text, "v1.2.3"); got != text {
		t.Fatalf("got %q", got)
	}
}

func TestTheOutputSaysWhereItComesFrom(t *testing.T) {
	got := render("# bonsai-lint\r\n", "v1.2.3")

	if !strings.HasPrefix(got, "<!-- Generated by internal/readme from https://github.com/ryckakas/bonsai-lint/blob/v1.2.3/README.md") {
		t.Fatalf("got %q", got)
	}
	if !strings.HasSuffix(got, "\n\n# bonsai-lint\n") {
		t.Fatalf("got %q", got)
	}
}

// README.md is generated, so a hand edit is lost at the next refresh; LAUNCHERS.md is the file to
// edit, and CI's README job checks that the copy matches bonsai-lint's latest release.
func TestTheCommittedReadmeIsTheGeneratedOne(t *testing.T) {
	committed, err := os.ReadFile(filepath.Join("..", "..", "README.md"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.HasPrefix(string(committed), "<!-- Generated by internal/readme from ") {
		t.Fatalf("README.md does not start with the generator's header")
	}
}
