// Code generated by internal/generate. DO NOT EDIT.

package main

const version = "0.5.0"

var archives = map[string]archive{
	"darwin/amd64":     {triple: "x86_64-apple-darwin", name: "bonsai-lint-x86_64-apple-darwin.tar.gz", sha256: "6b1bc36ab28c294d22b6dc28efa79db49597b6caa23287710ed16424c02ee68f", binary: "bonsai-lint"},
	"darwin/arm64":     {triple: "aarch64-apple-darwin", name: "bonsai-lint-aarch64-apple-darwin.tar.gz", sha256: "f4766dace114fa0b3f7acb6c022dc7dc169fb4fd4177477070c7fbfd6b02047b", binary: "bonsai-lint"},
	"linux/amd64":      {triple: "x86_64-unknown-linux-gnu", name: "bonsai-lint-x86_64-unknown-linux-gnu.tar.gz", sha256: "f94f571829496c35624bce9aa40277b09c8821d345519f1b6f65bbe5894f079c", binary: "bonsai-lint"},
	"linux/amd64/musl": {triple: "x86_64-unknown-linux-musl", name: "bonsai-lint-x86_64-unknown-linux-musl.tar.gz", sha256: "4661f70dbb407198396d956647516e0b441ea296b9baad083f4846a3c713ff2f", binary: "bonsai-lint"},
	"linux/arm64":      {triple: "aarch64-unknown-linux-gnu", name: "bonsai-lint-aarch64-unknown-linux-gnu.tar.gz", sha256: "d785304e56b76a635c03fb283f733975c7f78d6c2317ed2a2ff97ca5e8e93f7d", binary: "bonsai-lint"},
	"linux/arm64/musl": {triple: "aarch64-unknown-linux-musl", name: "bonsai-lint-aarch64-unknown-linux-musl.tar.gz", sha256: "f6e5ca59a19cad8a3ec603400feddd9ff4ed81e5efbcb3b129aee5fb2885339d", binary: "bonsai-lint"},
	"windows/amd64":    {triple: "x86_64-pc-windows-msvc", name: "bonsai-lint-x86_64-pc-windows-msvc.zip", sha256: "6aa22dd9ead981fcb778df361b215353b2770a297ff6acc83d9f9292851472c6", binary: "bonsai-lint.exe"},
	"windows/arm64":    {triple: "x86_64-pc-windows-msvc", name: "bonsai-lint-x86_64-pc-windows-msvc.zip", sha256: "6aa22dd9ead981fcb778df361b215353b2770a297ff6acc83d9f9292851472c6", binary: "bonsai-lint.exe"},
}
