<?php

// Code generated by internal/generate. DO NOT EDIT.

declare(strict_types=1);

namespace BonsaiLint\Composer;

final class Release
{
    public const VERSION = '0.4.3';

    public const ARCHIVES = [
        'aarch64-apple-darwin' => ['bonsai-lint-aarch64-apple-darwin.tar.gz', '56193625d451c2fd3c1cabd75c759a88c8404df54ad5629928c5e858bd843002'],
        'aarch64-unknown-linux-gnu' => ['bonsai-lint-aarch64-unknown-linux-gnu.tar.gz', 'a0585e912cc7959b291576d090f8ea99cde1faf07d70ea482aa16a0a76b6b741'],
        'aarch64-unknown-linux-musl' => ['bonsai-lint-aarch64-unknown-linux-musl.tar.gz', 'a792f7b2c3dfe12890d94e8248e3eccecbeeb576720ca0d0a3527efd360a0d80'],
        'x86_64-apple-darwin' => ['bonsai-lint-x86_64-apple-darwin.tar.gz', '11d61e74310f91b3a6aa1072d0fc9d5d6bf5a32825f8ec5b251941fd90ea16f6'],
        'x86_64-pc-windows-msvc' => ['bonsai-lint-x86_64-pc-windows-msvc.zip', '1a84ce34c5c0f02541dc6e90f90d30d51dc07fd83dbbddb6aa05aaeb5f9d119d'],
        'x86_64-unknown-linux-gnu' => ['bonsai-lint-x86_64-unknown-linux-gnu.tar.gz', '1f713640c8606721aad1a640f583063cfb8a9c73f803025cb4aa5da82efd0044'],
        'x86_64-unknown-linux-musl' => ['bonsai-lint-x86_64-unknown-linux-musl.tar.gz', '3167ab866391c34ba9b1c7ee38fa37ed68149e68a8b0305d0e5d340ace6aa535'],
    ];
}
