<?php

// Code generated by internal/generate. DO NOT EDIT.

declare(strict_types=1);

namespace BonsaiLint\Composer;

// An unreleased launcher: the release job replaces this file when it tags a version.
final class Release
{
    public const VERSION = '';

    public const ARCHIVES = [];
}
